namespace MESService
{
    public static class ConfigureService
    {
        public static IServiceCollection AddJWT(this IServiceCollection services)
        {

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
            {
                options.RequireHttpsMetadata = false;
                options.SaveToken = true;
                options.TokenValidationParameters = new TokenValidationParameters()
                {
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidAudience = GlobalHelper.Audience,
                    ValidIssuer = GlobalHelper.Issuer,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(GlobalHelper.Key))
                };
            });
            return services;
        }
        public static IServiceCollection AddContext(this IServiceCollection services)
        {
            //services.AddDbContext<Context>(opts => opts.UseMySql(GlobalHelper.MariaDBConectionString, ServerVersion.AutoDetect(GlobalHelper.MariaDBConectionString)));
            services.AddDbContext<Context>(opts => opts.UseMySql(GlobalHelper.MariaDBConectionString, ServerVersion.AutoDetect(GlobalHelper.MariaDBConectionString)));

            return services;
        }
        public static IServiceCollection AddService(this IServiceCollection services)
        {
            services.AddTransient<IaatableService, aatableService>();
            services.AddTransient<Iapqp_cdgrService, apqp_cdgrService>();
            services.AddTransient<Iapqp_codeService, apqp_codeService>();
            services.AddTransient<Iapqp_dlylstService, apqp_dlylstService>();
            services.AddTransient<Iapqp_filelstService, apqp_filelstService>();
            services.AddTransient<Iapqp_mstlstService, apqp_mstlstService>();
            services.AddTransient<Ikr_inspctn_stService, kr_inspctn_stService>();
            services.AddTransient<Ikr_inspctn_testService, kr_inspctn_testService>();
            services.AddTransient<Ikr_tdd_poplanService, kr_tdd_poplanService>();
            services.AddTransient<Ikr_tdpdmtimService, kr_tdpdmtimService>();
            services.AddTransient<Ikr_tdpdmtim_tmpService, kr_tdpdmtim_tmpService>();
            services.AddTransient<Ikr_tdpdmtim_tmp_outService, kr_tdpdmtim_tmp_outService>();
            services.AddTransient<Ikr_tdpdotplService, kr_tdpdotplService>();
            services.AddTransient<Ikr_tdpdotpl_inpoService, kr_tdpdotpl_inpoService>();
            services.AddTransient<Ikr_tiivtrService, kr_tiivtrService>();
            services.AddTransient<Ipd_asset_mmService, pd_asset_mmService>();
            services.AddTransient<Ipd_cmpny_costfileService, pd_cmpny_costfileService>();
            services.AddTransient<Ipd_cmpny_partService, pd_cmpny_partService>();
            services.AddTransient<Ipd_inout_partService, pd_inout_partService>();
            services.AddTransient<Ipd_mc_orderlistService, pd_mc_orderlistService>();
            services.AddTransient<Ipd_part_costService, pd_part_costService>();
            services.AddTransient<Ipd_tiivtrService, pd_tiivtrService>();
            services.AddTransient<IpdcdgrService, pdcdgrService>();
            services.AddTransient<IpdcdnmService, pdcdnmService>();
            services.AddTransient<IpdcmpnyService, pdcmpnyService>();
            services.AddTransient<IpdpartService, pdpartService>();
            services.AddTransient<Ipdpart_addlistService, pdpart_addlistService>();
            services.AddTransient<IpdpuschService, pdpuschService>();
            services.AddTransient<Itdd_ct_stService, tdd_ct_stService>();
            services.AddTransient<Itdd_poplanService, tdd_poplanService>();
            services.AddTransient<Itdd_poplan_djgService, tdd_poplan_djgService>();
            services.AddTransient<ItdpdmtimService, tdpdmtimService>();
            services.AddTransient<Itdpdmtim_autobc_listService, tdpdmtim_autobc_listService>();
            services.AddTransient<Itdpdmtim_delService, tdpdmtim_delService>();
            services.AddTransient<Itdpdmtim_histService, tdpdmtim_histService>();
            services.AddTransient<Itdpdmtim_locService, tdpdmtim_locService>();
            services.AddTransient<Itdpdmtim_reworkService, tdpdmtim_reworkService>();
            services.AddTransient<Itdpdmtim_tmpService, tdpdmtim_tmpService>();
            services.AddTransient<Itdpdmtin_serialService, tdpdmtin_serialService>();
            services.AddTransient<ItdpdotplService, tdpdotplService>();
            services.AddTransient<Itdpdotpl_alocService, tdpdotpl_alocService>();
            services.AddTransient<Itdpdotpl_etcService, tdpdotpl_etcService>();
            services.AddTransient<Itdpdotpl_labelService, tdpdotpl_labelService>();
            services.AddTransient<Itdpdotpl_tmpService, tdpdotpl_tmpService>();
            services.AddTransient<ItdpdotplmuService, tdpdotplmuService>();
            services.AddTransient<Itfg_monitorService, tfg_monitorService>();
            services.AddTransient<ItiivajService, tiivajService>();
            services.AddTransient<Itiivaj_historyService, tiivaj_historyService>();
            services.AddTransient<Itiivaj_leadService, tiivaj_leadService>();
            services.AddTransient<ItiivtrService, tiivtrService>();
            services.AddTransient<Itiivtr_excelService, tiivtr_excelService>();
            services.AddTransient<Itiivtr_historyService, tiivtr_historyService>();
            services.AddTransient<Itiivtr_leadService, tiivtr_leadService>();
            services.AddTransient<Itiivtr_lead_fgService, tiivtr_lead_fgService>();
            services.AddTransient<Itiivtr_lead_historyService, tiivtr_lead_historyService>();
            services.AddTransient<ItmbrcdService, tmbrcdService>();
            services.AddTransient<Itmbrcd_hisService, tmbrcd_hisService>();
            services.AddTransient<Itmbrcd_longtermService, tmbrcd_longtermService>();
            services.AddTransient<ItmmtinService, tmmtinService>();
            services.AddTransient<Itmmtin_dmmService, tmmtin_dmmService>();
            services.AddTransient<Itmmtin_dmm_appService, tmmtin_dmm_appService>();
            services.AddTransient<Itmmtin_dmm_cutService, tmmtin_dmm_cutService>();
            services.AddTransient<Itmmtin_dmm_leadService, tmmtin_dmm_leadService>();
            services.AddTransient<Itorder_barcodeService, torder_barcodeService>();
            services.AddTransient<Itorder_barcode_lpService, torder_barcode_lpService>();
            services.AddTransient<Itorder_barcode_spService, torder_barcode_spService>();
            services.AddTransient<Itorder_bomService, torder_bomService>();
            services.AddTransient<Itorder_bom_lpService, torder_bom_lpService>();
            services.AddTransient<Itorder_bom_not_climpService, torder_bom_not_climpService>();
            services.AddTransient<Itorder_bom_spst1Service, torder_bom_spst1Service>();
            services.AddTransient<Itorder_bom_spst2Service, torder_bom_spst2Service>();
            services.AddTransient<Itorder_bom_swService, torder_bom_swService>();
            services.AddTransient<Itorder_lead_bomService, torder_lead_bomService>();
            services.AddTransient<Itorder_lead_bom_exclService, torder_lead_bom_exclService>();
            services.AddTransient<Itorder_lead_bom_spstService, torder_lead_bom_spstService>();
            services.AddTransient<Itorder_lead_bom_spst_exclService, torder_lead_bom_spst_exclService>();
            services.AddTransient<Itorder_spcService, torder_spcService>();
            services.AddTransient<ItorderinspectionService, torderinspectionService>();
            services.AddTransient<Itorderinspection_lpService, torderinspection_lpService>();
            services.AddTransient<Itorderinspection_spstService, torderinspection_spstService>();
            services.AddTransient<Itorderinspection_swService, torderinspection_swService>();
            services.AddTransient<ItorderlistService, torderlistService>();
            services.AddTransient<Itorderlist_lpService, torderlist_lpService>();
            services.AddTransient<Itorderlist_lplistService, torderlist_lplistService>();
            services.AddTransient<Itorderlist_spstService, torderlist_spstService>();
            services.AddTransient<Itorderlist_swService, torderlist_swService>();
            services.AddTransient<Itorderlist_workService, torderlist_workService>();
            services.AddTransient<Itorderlist_wtimeService, torderlist_wtimeService>();
            services.AddTransient<Itrack_bc_tmpService, track_bc_tmpService>();
            services.AddTransient<ItrackmasterService, trackmasterService>();
            services.AddTransient<ItrackmtimService, trackmtimService>();
            services.AddTransient<Itrackmtim_lt_inspService, trackmtim_lt_inspService>();
            services.AddTransient<ItsauthService, tsauthService>();
            services.AddTransient<ItsbomService, tsbomService>();
            services.AddTransient<Itsbom_listService, tsbom_listService>();
            services.AddTransient<Itsbom_part_infService, tsbom_part_infService>();
            services.AddTransient<Itsbom_po_listService, tsbom_po_listService>();
            services.AddTransient<Itsbom_ver02Service, tsbom_ver02Service>();
            services.AddTransient<Itsbom_ver02_poService, tsbom_ver02_poService>();
            services.AddTransient<Itsbom_ver02_tmp1Service, tsbom_ver02_tmp1Service>();
            services.AddTransient<ItscdgrService, tscdgrService>();
            services.AddTransient<ItscmpnyService, tscmpnyService>();
            services.AddTransient<ItscodeService, tscodeService>();
            services.AddTransient<ItscostService, tscostService>();
            services.AddTransient<Itscost_listService, tscost_listService>();
            services.AddTransient<Itscut_st_uphService, tscut_st_uphService>();
            services.AddTransient<ItsmenuService, tsmenuService>();
            services.AddTransient<ItsmnauService, tsmnauService>();
            services.AddTransient<Itsmonitor_setService, tsmonitor_setService>();
            services.AddTransient<Itsnon_operService, tsnon_operService>();
            services.AddTransient<Itsnon_oper_andonService, tsnon_oper_andonService>();
            services.AddTransient<Itsnon_oper_andon_listService, tsnon_oper_andon_listService>();
            services.AddTransient<Itsnon_oper_mitorService, tsnon_oper_mitorService>();
            services.AddTransient<Itsnon_oper_workerService, tsnon_oper_workerService>();
            services.AddTransient<Itsnon_worktimeService, tsnon_worktimeService>();
            services.AddTransient<ItsnoticeService, tsnoticeService>();
            services.AddTransient<ItspartService, tspartService>();
            services.AddTransient<Itspart_addtnlService, tspart_addtnlService>();
            services.AddTransient<Itspart_ecnService, tspart_ecnService>();
            services.AddTransient<Itspart_fileService, tspart_fileService>();
            services.AddTransient<ItsurauService, tsurauService>();
            services.AddTransient<ItsuserService, tsuserService>();
            services.AddTransient<Itsuser_requService, tsuser_requService>();
            services.AddTransient<Itsuser_superService, tsuser_superService>();
            services.AddTransient<Itsyear_group_invService, tsyear_group_invService>();
            services.AddTransient<Itsyear_group_inv_histService, tsyear_group_inv_histService>();
            services.AddTransient<Itsyear_inventoryService, tsyear_inventoryService>();
            services.AddTransient<Itsyear_inventory_histService, tsyear_inventory_histService>();
            services.AddTransient<Ittc_barcodeService, ttc_barcodeService>();
            services.AddTransient<Ittc_bomService, ttc_bomService>();
            services.AddTransient<Ittc_orderService, ttc_orderService>();
            services.AddTransient<Ittc_partService, ttc_partService>();
            services.AddTransient<Ittc_rackmtinService, ttc_rackmtinService>();
            services.AddTransient<IttensilbndlstService, ttensilbndlstService>();
            services.AddTransient<IttensilforceService, ttensilforceService>();
            services.AddTransient<Ittensilforce_uswService, ttensilforce_uswService>();
            services.AddTransient<IttoolhistoryService, ttoolhistoryService>();
            services.AddTransient<IttoolmasterService, ttoolmasterService>();
            services.AddTransient<Ittoolmaster2Service, ttoolmaster2Service>();
            services.AddTransient<Ituser_logService, tuser_logService>();
            services.AddTransient<Ituser_log_chkService, tuser_log_chkService>();
            services.AddTransient<Ituser_log_chk_listService, tuser_log_chk_listService>();
            services.AddTransient<ItworkresultService, tworkresultService>();
            services.AddTransient<ItwtoolService, twtoolService>();
            services.AddTransient<ItwwkarService, twwkarService>();
            services.AddTransient<Itwwkar_lpService, twwkar_lpService>();
            services.AddTransient<Itwwkar_spstService, twwkar_spstService>();
            services.AddTransient<Ixsetting_timeService, xsetting_timeService>();
            services.AddTransient<Izadmin_functionService, zadmin_functionService>();
            services.AddTransient<Izt_devlpmnt_dbService, zt_devlpmnt_dbService>();
            services.AddTransient<Izt_help_dbService, zt_help_dbService>();
            services.AddTransient<Izt_log_dbService, zt_log_dbService>();
            services.AddTransient<Izz_mes_verService, zz_mes_verService>();

            services.AddSingleton(HtmlEncoder.Create(allowedRanges: new[] { UnicodeRanges.All }));

            return services;
        }

        public static IServiceCollection AddRepository(this IServiceCollection services)
        {
            services.AddTransient<IaatableRepository, aatableRepository>();
            services.AddTransient<Iapqp_cdgrRepository, apqp_cdgrRepository>();
            services.AddTransient<Iapqp_codeRepository, apqp_codeRepository>();
            services.AddTransient<Iapqp_dlylstRepository, apqp_dlylstRepository>();
            services.AddTransient<Iapqp_filelstRepository, apqp_filelstRepository>();
            services.AddTransient<Iapqp_mstlstRepository, apqp_mstlstRepository>();
            services.AddTransient<Ikr_inspctn_stRepository, kr_inspctn_stRepository>();
            services.AddTransient<Ikr_inspctn_testRepository, kr_inspctn_testRepository>();
            services.AddTransient<Ikr_tdd_poplanRepository, kr_tdd_poplanRepository>();
            services.AddTransient<Ikr_tdpdmtimRepository, kr_tdpdmtimRepository>();
            services.AddTransient<Ikr_tdpdmtim_tmpRepository, kr_tdpdmtim_tmpRepository>();
            services.AddTransient<Ikr_tdpdmtim_tmp_outRepository, kr_tdpdmtim_tmp_outRepository>();
            services.AddTransient<Ikr_tdpdotplRepository, kr_tdpdotplRepository>();
            services.AddTransient<Ikr_tdpdotpl_inpoRepository, kr_tdpdotpl_inpoRepository>();
            services.AddTransient<Ikr_tiivtrRepository, kr_tiivtrRepository>();
            services.AddTransient<Ipd_asset_mmRepository, pd_asset_mmRepository>();
            services.AddTransient<Ipd_cmpny_costfileRepository, pd_cmpny_costfileRepository>();
            services.AddTransient<Ipd_cmpny_partRepository, pd_cmpny_partRepository>();
            services.AddTransient<Ipd_inout_partRepository, pd_inout_partRepository>();
            services.AddTransient<Ipd_mc_orderlistRepository, pd_mc_orderlistRepository>();
            services.AddTransient<Ipd_part_costRepository, pd_part_costRepository>();
            services.AddTransient<Ipd_tiivtrRepository, pd_tiivtrRepository>();
            services.AddTransient<IpdcdgrRepository, pdcdgrRepository>();
            services.AddTransient<IpdcdnmRepository, pdcdnmRepository>();
            services.AddTransient<IpdcmpnyRepository, pdcmpnyRepository>();
            services.AddTransient<IpdpartRepository, pdpartRepository>();
            services.AddTransient<Ipdpart_addlistRepository, pdpart_addlistRepository>();
            services.AddTransient<IpdpuschRepository, pdpuschRepository>();
            services.AddTransient<Itdd_ct_stRepository, tdd_ct_stRepository>();
            services.AddTransient<Itdd_poplanRepository, tdd_poplanRepository>();
            services.AddTransient<Itdd_poplan_djgRepository, tdd_poplan_djgRepository>();
            services.AddTransient<ItdpdmtimRepository, tdpdmtimRepository>();
            services.AddTransient<Itdpdmtim_autobc_listRepository, tdpdmtim_autobc_listRepository>();
            services.AddTransient<Itdpdmtim_delRepository, tdpdmtim_delRepository>();
            services.AddTransient<Itdpdmtim_histRepository, tdpdmtim_histRepository>();
            services.AddTransient<Itdpdmtim_locRepository, tdpdmtim_locRepository>();
            services.AddTransient<Itdpdmtim_reworkRepository, tdpdmtim_reworkRepository>();
            services.AddTransient<Itdpdmtim_tmpRepository, tdpdmtim_tmpRepository>();
            services.AddTransient<Itdpdmtin_serialRepository, tdpdmtin_serialRepository>();
            services.AddTransient<ItdpdotplRepository, tdpdotplRepository>();
            services.AddTransient<Itdpdotpl_alocRepository, tdpdotpl_alocRepository>();
            services.AddTransient<Itdpdotpl_etcRepository, tdpdotpl_etcRepository>();
            services.AddTransient<Itdpdotpl_labelRepository, tdpdotpl_labelRepository>();
            services.AddTransient<Itdpdotpl_tmpRepository, tdpdotpl_tmpRepository>();
            services.AddTransient<ItdpdotplmuRepository, tdpdotplmuRepository>();
            services.AddTransient<Itfg_monitorRepository, tfg_monitorRepository>();
            services.AddTransient<ItiivajRepository, tiivajRepository>();
            services.AddTransient<Itiivaj_historyRepository, tiivaj_historyRepository>();
            services.AddTransient<Itiivaj_leadRepository, tiivaj_leadRepository>();
            services.AddTransient<ItiivtrRepository, tiivtrRepository>();
            services.AddTransient<Itiivtr_excelRepository, tiivtr_excelRepository>();
            services.AddTransient<Itiivtr_historyRepository, tiivtr_historyRepository>();
            services.AddTransient<Itiivtr_leadRepository, tiivtr_leadRepository>();
            services.AddTransient<Itiivtr_lead_fgRepository, tiivtr_lead_fgRepository>();
            services.AddTransient<Itiivtr_lead_historyRepository, tiivtr_lead_historyRepository>();
            services.AddTransient<ItmbrcdRepository, tmbrcdRepository>();
            services.AddTransient<Itmbrcd_hisRepository, tmbrcd_hisRepository>();
            services.AddTransient<Itmbrcd_longtermRepository, tmbrcd_longtermRepository>();
            services.AddTransient<ItmmtinRepository, tmmtinRepository>();
            services.AddTransient<Itmmtin_dmmRepository, tmmtin_dmmRepository>();
            services.AddTransient<Itmmtin_dmm_appRepository, tmmtin_dmm_appRepository>();
            services.AddTransient<Itmmtin_dmm_cutRepository, tmmtin_dmm_cutRepository>();
            services.AddTransient<Itmmtin_dmm_leadRepository, tmmtin_dmm_leadRepository>();
            services.AddTransient<Itorder_barcodeRepository, torder_barcodeRepository>();
            services.AddTransient<Itorder_barcode_lpRepository, torder_barcode_lpRepository>();
            services.AddTransient<Itorder_barcode_spRepository, torder_barcode_spRepository>();
            services.AddTransient<Itorder_bomRepository, torder_bomRepository>();
            services.AddTransient<Itorder_bom_lpRepository, torder_bom_lpRepository>();
            services.AddTransient<Itorder_bom_not_climpRepository, torder_bom_not_climpRepository>();
            services.AddTransient<Itorder_bom_spst1Repository, torder_bom_spst1Repository>();
            services.AddTransient<Itorder_bom_spst2Repository, torder_bom_spst2Repository>();
            services.AddTransient<Itorder_bom_swRepository, torder_bom_swRepository>();
            services.AddTransient<Itorder_lead_bomRepository, torder_lead_bomRepository>();
            services.AddTransient<Itorder_lead_bom_exclRepository, torder_lead_bom_exclRepository>();
            services.AddTransient<Itorder_lead_bom_spstRepository, torder_lead_bom_spstRepository>();
            services.AddTransient<Itorder_lead_bom_spst_exclRepository, torder_lead_bom_spst_exclRepository>();
            services.AddTransient<Itorder_spcRepository, torder_spcRepository>();
            services.AddTransient<ItorderinspectionRepository, torderinspectionRepository>();
            services.AddTransient<Itorderinspection_lpRepository, torderinspection_lpRepository>();
            services.AddTransient<Itorderinspection_spstRepository, torderinspection_spstRepository>();
            services.AddTransient<Itorderinspection_swRepository, torderinspection_swRepository>();
            services.AddTransient<ItorderlistRepository, torderlistRepository>();
            services.AddTransient<Itorderlist_lpRepository, torderlist_lpRepository>();
            services.AddTransient<Itorderlist_lplistRepository, torderlist_lplistRepository>();
            services.AddTransient<Itorderlist_spstRepository, torderlist_spstRepository>();
            services.AddTransient<Itorderlist_swRepository, torderlist_swRepository>();
            services.AddTransient<Itorderlist_workRepository, torderlist_workRepository>();
            services.AddTransient<Itorderlist_wtimeRepository, torderlist_wtimeRepository>();
            services.AddTransient<Itrack_bc_tmpRepository, track_bc_tmpRepository>();
            services.AddTransient<ItrackmasterRepository, trackmasterRepository>();
            services.AddTransient<ItrackmtimRepository, trackmtimRepository>();
            services.AddTransient<Itrackmtim_lt_inspRepository, trackmtim_lt_inspRepository>();
            services.AddTransient<ItsauthRepository, tsauthRepository>();
            services.AddTransient<ItsbomRepository, tsbomRepository>();
            services.AddTransient<Itsbom_listRepository, tsbom_listRepository>();
            services.AddTransient<Itsbom_part_infRepository, tsbom_part_infRepository>();
            services.AddTransient<Itsbom_po_listRepository, tsbom_po_listRepository>();
            services.AddTransient<Itsbom_ver02Repository, tsbom_ver02Repository>();
            services.AddTransient<Itsbom_ver02_poRepository, tsbom_ver02_poRepository>();
            services.AddTransient<Itsbom_ver02_tmp1Repository, tsbom_ver02_tmp1Repository>();
            services.AddTransient<ItscdgrRepository, tscdgrRepository>();
            services.AddTransient<ItscmpnyRepository, tscmpnyRepository>();
            services.AddTransient<ItscodeRepository, tscodeRepository>();
            services.AddTransient<ItscostRepository, tscostRepository>();
            services.AddTransient<Itscost_listRepository, tscost_listRepository>();
            services.AddTransient<Itscut_st_uphRepository, tscut_st_uphRepository>();
            services.AddTransient<ItsmenuRepository, tsmenuRepository>();
            services.AddTransient<ItsmnauRepository, tsmnauRepository>();
            services.AddTransient<Itsmonitor_setRepository, tsmonitor_setRepository>();
            services.AddTransient<Itsnon_operRepository, tsnon_operRepository>();
            services.AddTransient<Itsnon_oper_andonRepository, tsnon_oper_andonRepository>();
            services.AddTransient<Itsnon_oper_andon_listRepository, tsnon_oper_andon_listRepository>();
            services.AddTransient<Itsnon_oper_mitorRepository, tsnon_oper_mitorRepository>();
            services.AddTransient<Itsnon_oper_workerRepository, tsnon_oper_workerRepository>();
            services.AddTransient<Itsnon_worktimeRepository, tsnon_worktimeRepository>();
            services.AddTransient<ItsnoticeRepository, tsnoticeRepository>();
            services.AddTransient<ItspartRepository, tspartRepository>();
            services.AddTransient<Itspart_addtnlRepository, tspart_addtnlRepository>();
            services.AddTransient<Itspart_ecnRepository, tspart_ecnRepository>();
            services.AddTransient<Itspart_fileRepository, tspart_fileRepository>();
            services.AddTransient<ItsurauRepository, tsurauRepository>();
            services.AddTransient<ItsuserRepository, tsuserRepository>();
            services.AddTransient<Itsuser_requRepository, tsuser_requRepository>();
            services.AddTransient<Itsuser_superRepository, tsuser_superRepository>();
            services.AddTransient<Itsyear_group_invRepository, tsyear_group_invRepository>();
            services.AddTransient<Itsyear_group_inv_histRepository, tsyear_group_inv_histRepository>();
            services.AddTransient<Itsyear_inventoryRepository, tsyear_inventoryRepository>();
            services.AddTransient<Itsyear_inventory_histRepository, tsyear_inventory_histRepository>();
            services.AddTransient<Ittc_barcodeRepository, ttc_barcodeRepository>();
            services.AddTransient<Ittc_bomRepository, ttc_bomRepository>();
            services.AddTransient<Ittc_orderRepository, ttc_orderRepository>();
            services.AddTransient<Ittc_partRepository, ttc_partRepository>();
            services.AddTransient<Ittc_rackmtinRepository, ttc_rackmtinRepository>();
            services.AddTransient<IttensilbndlstRepository, ttensilbndlstRepository>();
            services.AddTransient<IttensilforceRepository, ttensilforceRepository>();
            services.AddTransient<Ittensilforce_uswRepository, ttensilforce_uswRepository>();
            services.AddTransient<IttoolhistoryRepository, ttoolhistoryRepository>();
            services.AddTransient<IttoolmasterRepository, ttoolmasterRepository>();
            services.AddTransient<Ittoolmaster2Repository, ttoolmaster2Repository>();
            services.AddTransient<Ituser_logRepository, tuser_logRepository>();
            services.AddTransient<Ituser_log_chkRepository, tuser_log_chkRepository>();
            services.AddTransient<Ituser_log_chk_listRepository, tuser_log_chk_listRepository>();
            services.AddTransient<ItworkresultRepository, tworkresultRepository>();
            services.AddTransient<ItwtoolRepository, twtoolRepository>();
            services.AddTransient<ItwwkarRepository, twwkarRepository>();
            services.AddTransient<Itwwkar_lpRepository, twwkar_lpRepository>();
            services.AddTransient<Itwwkar_spstRepository, twwkar_spstRepository>();
            services.AddTransient<Ixsetting_timeRepository, xsetting_timeRepository>();
            services.AddTransient<Izadmin_functionRepository, zadmin_functionRepository>();
            services.AddTransient<Izt_devlpmnt_dbRepository, zt_devlpmnt_dbRepository>();
            services.AddTransient<Izt_help_dbRepository, zt_help_dbRepository>();
            services.AddTransient<Izt_log_dbRepository, zt_log_dbRepository>();
            services.AddTransient<Izz_mes_verRepository, zz_mes_verRepository>();

            return services;
        }
    }
}

