namespace MESService.Model
{
	public partial class BaseResult : BaseModel
    {     
        public List<aatable>? Listaatable { get; set; }
public List<aatableTranfer>? ListaatableTranfer { get; set; }
public List<apqp_cdgr>? Listapqp_cdgr { get; set; }
public List<apqp_cdgrTranfer>? Listapqp_cdgrTranfer { get; set; }
public List<apqp_code>? Listapqp_code { get; set; }
public List<apqp_codeTranfer>? Listapqp_codeTranfer { get; set; }
public List<apqp_dlylst>? Listapqp_dlylst { get; set; }
public List<apqp_dlylstTranfer>? Listapqp_dlylstTranfer { get; set; }
public List<apqp_filelst>? Listapqp_filelst { get; set; }
public List<apqp_filelstTranfer>? Listapqp_filelstTranfer { get; set; }
public List<apqp_mstlst>? Listapqp_mstlst { get; set; }
public List<apqp_mstlstTranfer>? Listapqp_mstlstTranfer { get; set; }
public List<kr_inspctn_st>? Listkr_inspctn_st { get; set; }
public List<kr_inspctn_stTranfer>? Listkr_inspctn_stTranfer { get; set; }
public List<kr_inspctn_test>? Listkr_inspctn_test { get; set; }
public List<kr_inspctn_testTranfer>? Listkr_inspctn_testTranfer { get; set; }
public List<kr_tdd_poplan>? Listkr_tdd_poplan { get; set; }
public List<kr_tdd_poplanTranfer>? Listkr_tdd_poplanTranfer { get; set; }
public List<kr_tdpdmtim>? Listkr_tdpdmtim { get; set; }
public List<kr_tdpdmtimTranfer>? Listkr_tdpdmtimTranfer { get; set; }
public List<kr_tdpdmtim_tmp>? Listkr_tdpdmtim_tmp { get; set; }
public List<kr_tdpdmtim_tmpTranfer>? Listkr_tdpdmtim_tmpTranfer { get; set; }
public List<kr_tdpdmtim_tmp_out>? Listkr_tdpdmtim_tmp_out { get; set; }
public List<kr_tdpdmtim_tmp_outTranfer>? Listkr_tdpdmtim_tmp_outTranfer { get; set; }
public List<kr_tdpdotpl>? Listkr_tdpdotpl { get; set; }
public List<kr_tdpdotplTranfer>? Listkr_tdpdotplTranfer { get; set; }
public List<kr_tdpdotpl_inpo>? Listkr_tdpdotpl_inpo { get; set; }
public List<kr_tdpdotpl_inpoTranfer>? Listkr_tdpdotpl_inpoTranfer { get; set; }
public List<kr_tiivtr>? Listkr_tiivtr { get; set; }
public List<kr_tiivtrTranfer>? Listkr_tiivtrTranfer { get; set; }
public List<pd_asset_mm>? Listpd_asset_mm { get; set; }
public List<pd_asset_mmTranfer>? Listpd_asset_mmTranfer { get; set; }
public List<pd_cmpny_costfile>? Listpd_cmpny_costfile { get; set; }
public List<pd_cmpny_costfileTranfer>? Listpd_cmpny_costfileTranfer { get; set; }
public List<pd_cmpny_part>? Listpd_cmpny_part { get; set; }
public List<pd_cmpny_partTranfer>? Listpd_cmpny_partTranfer { get; set; }
public List<pd_inout_part>? Listpd_inout_part { get; set; }
public List<pd_inout_partTranfer>? Listpd_inout_partTranfer { get; set; }
public List<pd_mc_orderlist>? Listpd_mc_orderlist { get; set; }
public List<pd_mc_orderlistTranfer>? Listpd_mc_orderlistTranfer { get; set; }
public List<pd_part_cost>? Listpd_part_cost { get; set; }
public List<pd_part_costTranfer>? Listpd_part_costTranfer { get; set; }
public List<pd_tiivtr>? Listpd_tiivtr { get; set; }
public List<pd_tiivtrTranfer>? Listpd_tiivtrTranfer { get; set; }
public List<pdcdgr>? Listpdcdgr { get; set; }
public List<pdcdgrTranfer>? ListpdcdgrTranfer { get; set; }
public List<pdcdnm>? Listpdcdnm { get; set; }
public List<pdcdnmTranfer>? ListpdcdnmTranfer { get; set; }
public List<pdcmpny>? Listpdcmpny { get; set; }
public List<pdcmpnyTranfer>? ListpdcmpnyTranfer { get; set; }
public List<pdpart>? Listpdpart { get; set; }
public List<pdpartTranfer>? ListpdpartTranfer { get; set; }
public List<pdpart_addlist>? Listpdpart_addlist { get; set; }
public List<pdpart_addlistTranfer>? Listpdpart_addlistTranfer { get; set; }
public List<pdpusch>? Listpdpusch { get; set; }
public List<pdpuschTranfer>? ListpdpuschTranfer { get; set; }
public List<tdd_ct_st>? Listtdd_ct_st { get; set; }
public List<tdd_ct_stTranfer>? Listtdd_ct_stTranfer { get; set; }
public List<tdd_poplan>? Listtdd_poplan { get; set; }
public List<tdd_poplanTranfer>? Listtdd_poplanTranfer { get; set; }
public List<tdd_poplan_djg>? Listtdd_poplan_djg { get; set; }
public List<tdd_poplan_djgTranfer>? Listtdd_poplan_djgTranfer { get; set; }
public List<tdpdmtim>? Listtdpdmtim { get; set; }
public List<tdpdmtimTranfer>? ListtdpdmtimTranfer { get; set; }
public List<tdpdmtim_autobc_list>? Listtdpdmtim_autobc_list { get; set; }
public List<tdpdmtim_autobc_listTranfer>? Listtdpdmtim_autobc_listTranfer { get; set; }
public List<tdpdmtim_del>? Listtdpdmtim_del { get; set; }
public List<tdpdmtim_delTranfer>? Listtdpdmtim_delTranfer { get; set; }
public List<tdpdmtim_hist>? Listtdpdmtim_hist { get; set; }
public List<tdpdmtim_histTranfer>? Listtdpdmtim_histTranfer { get; set; }
public List<tdpdmtim_loc>? Listtdpdmtim_loc { get; set; }
public List<tdpdmtim_locTranfer>? Listtdpdmtim_locTranfer { get; set; }
public List<tdpdmtim_rework>? Listtdpdmtim_rework { get; set; }
public List<tdpdmtim_reworkTranfer>? Listtdpdmtim_reworkTranfer { get; set; }
public List<tdpdmtim_tmp>? Listtdpdmtim_tmp { get; set; }
public List<tdpdmtim_tmpTranfer>? Listtdpdmtim_tmpTranfer { get; set; }
public List<tdpdmtin_serial>? Listtdpdmtin_serial { get; set; }
public List<tdpdmtin_serialTranfer>? Listtdpdmtin_serialTranfer { get; set; }
public List<tdpdotpl>? Listtdpdotpl { get; set; }
public List<tdpdotplTranfer>? ListtdpdotplTranfer { get; set; }
public List<tdpdotpl_aloc>? Listtdpdotpl_aloc { get; set; }
public List<tdpdotpl_alocTranfer>? Listtdpdotpl_alocTranfer { get; set; }
public List<tdpdotpl_etc>? Listtdpdotpl_etc { get; set; }
public List<tdpdotpl_etcTranfer>? Listtdpdotpl_etcTranfer { get; set; }
public List<tdpdotpl_label>? Listtdpdotpl_label { get; set; }
public List<tdpdotpl_labelTranfer>? Listtdpdotpl_labelTranfer { get; set; }
public List<tdpdotpl_tmp>? Listtdpdotpl_tmp { get; set; }
public List<tdpdotpl_tmpTranfer>? Listtdpdotpl_tmpTranfer { get; set; }
public List<tdpdotplmu>? Listtdpdotplmu { get; set; }
public List<tdpdotplmuTranfer>? ListtdpdotplmuTranfer { get; set; }
public List<tfg_monitor>? Listtfg_monitor { get; set; }
public List<tfg_monitorTranfer>? Listtfg_monitorTranfer { get; set; }
public List<tiivaj>? Listtiivaj { get; set; }
public List<tiivajTranfer>? ListtiivajTranfer { get; set; }
public List<tiivaj_history>? Listtiivaj_history { get; set; }
public List<tiivaj_historyTranfer>? Listtiivaj_historyTranfer { get; set; }
public List<tiivaj_lead>? Listtiivaj_lead { get; set; }
public List<tiivaj_leadTranfer>? Listtiivaj_leadTranfer { get; set; }
public List<tiivtr>? Listtiivtr { get; set; }
public List<tiivtrTranfer>? ListtiivtrTranfer { get; set; }
public List<tiivtr_excel>? Listtiivtr_excel { get; set; }
public List<tiivtr_excelTranfer>? Listtiivtr_excelTranfer { get; set; }
public List<tiivtr_history>? Listtiivtr_history { get; set; }
public List<tiivtr_historyTranfer>? Listtiivtr_historyTranfer { get; set; }
public List<tiivtr_lead>? Listtiivtr_lead { get; set; }
public List<tiivtr_leadTranfer>? Listtiivtr_leadTranfer { get; set; }
public List<tiivtr_lead_fg>? Listtiivtr_lead_fg { get; set; }
public List<tiivtr_lead_fgTranfer>? Listtiivtr_lead_fgTranfer { get; set; }
public List<tiivtr_lead_history>? Listtiivtr_lead_history { get; set; }
public List<tiivtr_lead_historyTranfer>? Listtiivtr_lead_historyTranfer { get; set; }
public List<tmbrcd>? Listtmbrcd { get; set; }
public List<tmbrcdTranfer>? ListtmbrcdTranfer { get; set; }
public List<tmbrcd_his>? Listtmbrcd_his { get; set; }
public List<tmbrcd_hisTranfer>? Listtmbrcd_hisTranfer { get; set; }
public List<tmbrcd_longterm>? Listtmbrcd_longterm { get; set; }
public List<tmbrcd_longtermTranfer>? Listtmbrcd_longtermTranfer { get; set; }
public List<tmmtin>? Listtmmtin { get; set; }
public List<tmmtinTranfer>? ListtmmtinTranfer { get; set; }
public List<tmmtin_dmm>? Listtmmtin_dmm { get; set; }
public List<tmmtin_dmmTranfer>? Listtmmtin_dmmTranfer { get; set; }
public List<tmmtin_dmm_app>? Listtmmtin_dmm_app { get; set; }
public List<tmmtin_dmm_appTranfer>? Listtmmtin_dmm_appTranfer { get; set; }
public List<tmmtin_dmm_cut>? Listtmmtin_dmm_cut { get; set; }
public List<tmmtin_dmm_cutTranfer>? Listtmmtin_dmm_cutTranfer { get; set; }
public List<tmmtin_dmm_lead>? Listtmmtin_dmm_lead { get; set; }
public List<tmmtin_dmm_leadTranfer>? Listtmmtin_dmm_leadTranfer { get; set; }
public List<torder_barcode>? Listtorder_barcode { get; set; }
public List<torder_barcodeTranfer>? Listtorder_barcodeTranfer { get; set; }
public List<torder_barcode_lp>? Listtorder_barcode_lp { get; set; }
public List<torder_barcode_lpTranfer>? Listtorder_barcode_lpTranfer { get; set; }
public List<torder_barcode_sp>? Listtorder_barcode_sp { get; set; }
public List<torder_barcode_spTranfer>? Listtorder_barcode_spTranfer { get; set; }
public List<torder_bom>? Listtorder_bom { get; set; }
public List<torder_bomTranfer>? Listtorder_bomTranfer { get; set; }
public List<torder_bom_lp>? Listtorder_bom_lp { get; set; }
public List<torder_bom_lpTranfer>? Listtorder_bom_lpTranfer { get; set; }
public List<torder_bom_not_climp>? Listtorder_bom_not_climp { get; set; }
public List<torder_bom_not_climpTranfer>? Listtorder_bom_not_climpTranfer { get; set; }
public List<torder_bom_spst1>? Listtorder_bom_spst1 { get; set; }
public List<torder_bom_spst1Tranfer>? Listtorder_bom_spst1Tranfer { get; set; }
public List<torder_bom_spst2>? Listtorder_bom_spst2 { get; set; }
public List<torder_bom_spst2Tranfer>? Listtorder_bom_spst2Tranfer { get; set; }
public List<torder_bom_sw>? Listtorder_bom_sw { get; set; }
public List<torder_bom_swTranfer>? Listtorder_bom_swTranfer { get; set; }
public List<torder_lead_bom>? Listtorder_lead_bom { get; set; }
public List<torder_lead_bomTranfer>? Listtorder_lead_bomTranfer { get; set; }
public List<torder_lead_bom_excl>? Listtorder_lead_bom_excl { get; set; }
public List<torder_lead_bom_exclTranfer>? Listtorder_lead_bom_exclTranfer { get; set; }
public List<torder_lead_bom_spst>? Listtorder_lead_bom_spst { get; set; }
public List<torder_lead_bom_spstTranfer>? Listtorder_lead_bom_spstTranfer { get; set; }
public List<torder_lead_bom_spst_excl>? Listtorder_lead_bom_spst_excl { get; set; }
public List<torder_lead_bom_spst_exclTranfer>? Listtorder_lead_bom_spst_exclTranfer { get; set; }
public List<torder_spc>? Listtorder_spc { get; set; }
public List<torder_spcTranfer>? Listtorder_spcTranfer { get; set; }
public List<torderinspection>? Listtorderinspection { get; set; }
public List<torderinspectionTranfer>? ListtorderinspectionTranfer { get; set; }
public List<torderinspection_lp>? Listtorderinspection_lp { get; set; }
public List<torderinspection_lpTranfer>? Listtorderinspection_lpTranfer { get; set; }
public List<torderinspection_spst>? Listtorderinspection_spst { get; set; }
public List<torderinspection_spstTranfer>? Listtorderinspection_spstTranfer { get; set; }
public List<torderinspection_sw>? Listtorderinspection_sw { get; set; }
public List<torderinspection_swTranfer>? Listtorderinspection_swTranfer { get; set; }
public List<torderlist>? Listtorderlist { get; set; }
public List<torderlistTranfer>? ListtorderlistTranfer { get; set; }
public List<torderlist_lp>? Listtorderlist_lp { get; set; }
public List<torderlist_lpTranfer>? Listtorderlist_lpTranfer { get; set; }
public List<torderlist_lplist>? Listtorderlist_lplist { get; set; }
public List<torderlist_lplistTranfer>? Listtorderlist_lplistTranfer { get; set; }
public List<torderlist_spst>? Listtorderlist_spst { get; set; }
public List<torderlist_spstTranfer>? Listtorderlist_spstTranfer { get; set; }
public List<torderlist_sw>? Listtorderlist_sw { get; set; }
public List<torderlist_swTranfer>? Listtorderlist_swTranfer { get; set; }
public List<torderlist_work>? Listtorderlist_work { get; set; }
public List<torderlist_workTranfer>? Listtorderlist_workTranfer { get; set; }
public List<torderlist_wtime>? Listtorderlist_wtime { get; set; }
public List<torderlist_wtimeTranfer>? Listtorderlist_wtimeTranfer { get; set; }
public List<track_bc_tmp>? Listtrack_bc_tmp { get; set; }
public List<track_bc_tmpTranfer>? Listtrack_bc_tmpTranfer { get; set; }
public List<trackmaster>? Listtrackmaster { get; set; }
public List<trackmasterTranfer>? ListtrackmasterTranfer { get; set; }
public List<trackmtim>? Listtrackmtim { get; set; }
public List<trackmtimTranfer>? ListtrackmtimTranfer { get; set; }
public List<trackmtim_lt_insp>? Listtrackmtim_lt_insp { get; set; }
public List<trackmtim_lt_inspTranfer>? Listtrackmtim_lt_inspTranfer { get; set; }
public List<tsauth>? Listtsauth { get; set; }
public List<tsauthTranfer>? ListtsauthTranfer { get; set; }
public List<tsbom>? Listtsbom { get; set; }
public List<tsbomTranfer>? ListtsbomTranfer { get; set; }
public List<tsbom_list>? Listtsbom_list { get; set; }
public List<tsbom_listTranfer>? Listtsbom_listTranfer { get; set; }
public List<tsbom_part_inf>? Listtsbom_part_inf { get; set; }
public List<tsbom_part_infTranfer>? Listtsbom_part_infTranfer { get; set; }
public List<tsbom_po_list>? Listtsbom_po_list { get; set; }
public List<tsbom_po_listTranfer>? Listtsbom_po_listTranfer { get; set; }
public List<tsbom_ver02>? Listtsbom_ver02 { get; set; }
public List<tsbom_ver02Tranfer>? Listtsbom_ver02Tranfer { get; set; }
public List<tsbom_ver02_po>? Listtsbom_ver02_po { get; set; }
public List<tsbom_ver02_poTranfer>? Listtsbom_ver02_poTranfer { get; set; }
public List<tsbom_ver02_tmp1>? Listtsbom_ver02_tmp1 { get; set; }
public List<tsbom_ver02_tmp1Tranfer>? Listtsbom_ver02_tmp1Tranfer { get; set; }
public List<tscdgr>? Listtscdgr { get; set; }
public List<tscdgrTranfer>? ListtscdgrTranfer { get; set; }
public List<tscmpny>? Listtscmpny { get; set; }
public List<tscmpnyTranfer>? ListtscmpnyTranfer { get; set; }
public List<tscode>? Listtscode { get; set; }
public List<tscodeTranfer>? ListtscodeTranfer { get; set; }
public List<tscost>? Listtscost { get; set; }
public List<tscostTranfer>? ListtscostTranfer { get; set; }
public List<tscost_list>? Listtscost_list { get; set; }
public List<tscost_listTranfer>? Listtscost_listTranfer { get; set; }
public List<tscut_st_uph>? Listtscut_st_uph { get; set; }
public List<tscut_st_uphTranfer>? Listtscut_st_uphTranfer { get; set; }
public List<tsmenu>? Listtsmenu { get; set; }
public List<tsmenuTranfer>? ListtsmenuTranfer { get; set; }
public List<tsmnau>? Listtsmnau { get; set; }
public List<tsmnauTranfer>? ListtsmnauTranfer { get; set; }
public List<tsmonitor_set>? Listtsmonitor_set { get; set; }
public List<tsmonitor_setTranfer>? Listtsmonitor_setTranfer { get; set; }
public List<tsnon_oper>? Listtsnon_oper { get; set; }
public List<tsnon_operTranfer>? Listtsnon_operTranfer { get; set; }
public List<tsnon_oper_andon>? Listtsnon_oper_andon { get; set; }
public List<tsnon_oper_andonTranfer>? Listtsnon_oper_andonTranfer { get; set; }
public List<tsnon_oper_andon_list>? Listtsnon_oper_andon_list { get; set; }
public List<tsnon_oper_andon_listTranfer>? Listtsnon_oper_andon_listTranfer { get; set; }
public List<tsnon_oper_mitor>? Listtsnon_oper_mitor { get; set; }
public List<tsnon_oper_mitorTranfer>? Listtsnon_oper_mitorTranfer { get; set; }
public List<tsnon_oper_worker>? Listtsnon_oper_worker { get; set; }
public List<tsnon_oper_workerTranfer>? Listtsnon_oper_workerTranfer { get; set; }
public List<tsnon_worktime>? Listtsnon_worktime { get; set; }
public List<tsnon_worktimeTranfer>? Listtsnon_worktimeTranfer { get; set; }
public List<tsnotice>? Listtsnotice { get; set; }
public List<tsnoticeTranfer>? ListtsnoticeTranfer { get; set; }
public List<tspart>? Listtspart { get; set; }
public List<tspartTranfer>? ListtspartTranfer { get; set; }
public List<tspart_addtnl>? Listtspart_addtnl { get; set; }
public List<tspart_addtnlTranfer>? Listtspart_addtnlTranfer { get; set; }
public List<tspart_ecn>? Listtspart_ecn { get; set; }
public List<tspart_ecnTranfer>? Listtspart_ecnTranfer { get; set; }
public List<tspart_file>? Listtspart_file { get; set; }
public List<tspart_fileTranfer>? Listtspart_fileTranfer { get; set; }
public List<tsurau>? Listtsurau { get; set; }
public List<tsurauTranfer>? ListtsurauTranfer { get; set; }
public List<tsuser>? Listtsuser { get; set; }
public List<tsuserTranfer>? ListtsuserTranfer { get; set; }
public List<tsuser_requ>? Listtsuser_requ { get; set; }
public List<tsuser_requTranfer>? Listtsuser_requTranfer { get; set; }
public List<tsuser_super>? Listtsuser_super { get; set; }
public List<tsuser_superTranfer>? Listtsuser_superTranfer { get; set; }
public List<tsyear_group_inv>? Listtsyear_group_inv { get; set; }
public List<tsyear_group_invTranfer>? Listtsyear_group_invTranfer { get; set; }
public List<tsyear_group_inv_hist>? Listtsyear_group_inv_hist { get; set; }
public List<tsyear_group_inv_histTranfer>? Listtsyear_group_inv_histTranfer { get; set; }
public List<tsyear_inventory>? Listtsyear_inventory { get; set; }
public List<tsyear_inventoryTranfer>? Listtsyear_inventoryTranfer { get; set; }
public List<tsyear_inventory_hist>? Listtsyear_inventory_hist { get; set; }
public List<tsyear_inventory_histTranfer>? Listtsyear_inventory_histTranfer { get; set; }
public List<ttc_barcode>? Listttc_barcode { get; set; }
public List<ttc_barcodeTranfer>? Listttc_barcodeTranfer { get; set; }
public List<ttc_bom>? Listttc_bom { get; set; }
public List<ttc_bomTranfer>? Listttc_bomTranfer { get; set; }
public List<ttc_order>? Listttc_order { get; set; }
public List<ttc_orderTranfer>? Listttc_orderTranfer { get; set; }
public List<ttc_part>? Listttc_part { get; set; }
public List<ttc_partTranfer>? Listttc_partTranfer { get; set; }
public List<ttc_rackmtin>? Listttc_rackmtin { get; set; }
public List<ttc_rackmtinTranfer>? Listttc_rackmtinTranfer { get; set; }
public List<ttensilbndlst>? Listttensilbndlst { get; set; }
public List<ttensilbndlstTranfer>? ListttensilbndlstTranfer { get; set; }
public List<ttensilforce>? Listttensilforce { get; set; }
public List<ttensilforceTranfer>? ListttensilforceTranfer { get; set; }
public List<ttensilforce_usw>? Listttensilforce_usw { get; set; }
public List<ttensilforce_uswTranfer>? Listttensilforce_uswTranfer { get; set; }
public List<ttoolhistory>? Listttoolhistory { get; set; }
public List<ttoolhistoryTranfer>? ListttoolhistoryTranfer { get; set; }
public List<ttoolmaster>? Listttoolmaster { get; set; }
public List<ttoolmasterTranfer>? ListttoolmasterTranfer { get; set; }
public List<ttoolmaster2>? Listttoolmaster2 { get; set; }
public List<ttoolmaster2Tranfer>? Listttoolmaster2Tranfer { get; set; }
public List<tuser_log>? Listtuser_log { get; set; }
public List<tuser_logTranfer>? Listtuser_logTranfer { get; set; }
public List<tuser_log_chk>? Listtuser_log_chk { get; set; }
public List<tuser_log_chkTranfer>? Listtuser_log_chkTranfer { get; set; }
public List<tuser_log_chk_list>? Listtuser_log_chk_list { get; set; }
public List<tuser_log_chk_listTranfer>? Listtuser_log_chk_listTranfer { get; set; }
public List<tworkresult>? Listtworkresult { get; set; }
public List<tworkresultTranfer>? ListtworkresultTranfer { get; set; }
public List<twtool>? Listtwtool { get; set; }
public List<twtoolTranfer>? ListtwtoolTranfer { get; set; }
public List<twwkar>? Listtwwkar { get; set; }
public List<twwkarTranfer>? ListtwwkarTranfer { get; set; }
public List<twwkar_lp>? Listtwwkar_lp { get; set; }
public List<twwkar_lpTranfer>? Listtwwkar_lpTranfer { get; set; }
public List<twwkar_spst>? Listtwwkar_spst { get; set; }
public List<twwkar_spstTranfer>? Listtwwkar_spstTranfer { get; set; }
public List<xsetting_time>? Listxsetting_time { get; set; }
public List<xsetting_timeTranfer>? Listxsetting_timeTranfer { get; set; }
public List<zadmin_function>? Listzadmin_function { get; set; }
public List<zadmin_functionTranfer>? Listzadmin_functionTranfer { get; set; }
public List<zt_devlpmnt_db>? Listzt_devlpmnt_db { get; set; }
public List<zt_devlpmnt_dbTranfer>? Listzt_devlpmnt_dbTranfer { get; set; }
public List<zt_help_db>? Listzt_help_db { get; set; }
public List<zt_help_dbTranfer>? Listzt_help_dbTranfer { get; set; }
public List<zt_log_db>? Listzt_log_db { get; set; }
public List<zt_log_dbTranfer>? Listzt_log_dbTranfer { get; set; }
public List<zz_mes_ver>? Listzz_mes_ver { get; set; }
public List<zz_mes_verTranfer>? Listzz_mes_verTranfer { get; set; }

        public BaseResult()
        {
        }
    }
}

